apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
  labels:
    app: customer-service
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
        tier: customer-service
    spec:
      containers:
      - name: customer-service
        image: nerdulent/customer-microservice:16
        imagePullPolicy: Always
        ports:
        - containerPort: 3333
          name: customer-port
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
  labels:
    app: customer-service
spec:
  ports:
    - port: 3333
      targetPort: 5000
  selector:
    app: customer-service
    tier: customer-service
  type: LoadBalancer
